# Generated by Django 4.0 on 2022-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('date_stamp', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usd', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('eur', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('rub', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('uah', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('jpy', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('cny', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('cur_name', models.CharField(max_length=100)),
                ('cur_abbrev', models.CharField(max_length=5)),
                ('number_unit', models.IntegerField()),
                ('nbrb_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nbrb_code_static', models.CharField(max_length=3)),
                ('cur_date_start', models.DateField()),
                ('cur_date_end', models.DateField()),
            ],
        ),
    ]
