# Generated by Django 4.0 on 2022-01-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_stamp',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
