# Generated by Django 4.0 on 2022-01-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_course_date_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='cur_date_end',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='cur_date_start',
            field=models.CharField(max_length=10),
        ),
    ]
